In [287]:

from IPython.core.display import display, HTML
display(HTML(
"""<style>
div.container { width:100% !important; }
div.CodeMirror {font-family: Consolas; font-size: 25pt;}
div.output { font-size: 16pt; font-weight: bold;}
div.input { font-family: Consolas; font-size: 25pt;}
div.prompt { min-width: 100px;}
</style>
"""))

In [4]:
## 파일 입출력
## 데이터를 파일에 저장하거나 파일에 있는 데이터를 가져오고자 할 때 사용
## 파일에 데이터를 저장
# f = open("C:/Users/soldesk/Desktop/python2110/test1.txt","w")
f = open("test1.txt","w")
f.write("1번째 줄입니다.\n")
f.write("2번째 줄입니다.\n")
f.write("3번째 줄입니다.\n")
f.write("4번째 줄입니다.\n")
f.close()

In [5]:
f = open("test1.txt","w") # 있는 파일에 내용 적으면  overwrite가 된다.
f.write("5번째 줄입니다.\n")
f.write("6번째 줄입니다.\n")
f.write("7번째 줄입니다.\n")
f.write("8번째 줄입니다.\n")
f.close()

In [6]:
f = open("test1.txt","w")
for i in range(1, 21):
    f.write(f"{i}번째 줄입니다.\n")
f.close()

In [7]:
f = open("test1.txt","a")
for i in range(21, 41):
    f.write(f"{i}번째 줄입니다.\n")
f.close()

In [13]:
#### 파일안에 있는 내용을 읽어 오기
f = open("test1.txt","r")
line = f.readline()
print(line)
line = f.readline()
print(line)
line = f.readline()
print(line)
f.close()
'''
line = f.readline() # 파일이 닫혀서 오류 발생
print(line)
'''

1번째 줄입니다.

2번째 줄입니다.

3번째 줄입니다.



'\nline = f.readline() # 파일이 닫혀서 오류 발생\nprint(line)\n'

In [14]:
f = open("test1.txt","r")
while True:
    line = f.readline() # 한행 씩 읽어 올때 사용하는 것이 좋다.
    if not line: # 데이터를 읽어 오지 못하면 False이다. not False = True
        break
    print(line)
f.close()

1번째 줄입니다.

2번째 줄입니다.

3번째 줄입니다.

4번째 줄입니다.

5번째 줄입니다.

6번째 줄입니다.

7번째 줄입니다.

8번째 줄입니다.

9번째 줄입니다.

10번째 줄입니다.

11번째 줄입니다.

12번째 줄입니다.

13번째 줄입니다.

14번째 줄입니다.

15번째 줄입니다.

16번째 줄입니다.

17번째 줄입니다.

18번째 줄입니다.

19번째 줄입니다.

20번째 줄입니다.

21번째 줄입니다.

22번째 줄입니다.

23번째 줄입니다.

24번째 줄입니다.

25번째 줄입니다.

26번째 줄입니다.

27번째 줄입니다.

28번째 줄입니다.

29번째 줄입니다.

30번째 줄입니다.

31번째 줄입니다.

32번째 줄입니다.

33번째 줄입니다.

34번째 줄입니다.

35번째 줄입니다.

36번째 줄입니다.

37번째 줄입니다.

38번째 줄입니다.

39번째 줄입니다.

40번째 줄입니다.



In [20]:
f = open("test1.txt","r")
lines = f.readlines() ### 파일 내용의 행(\n)을 요소하는 리스트로 받아옴
f.close()
print(lines)

print("==" * 30)
for line in lines:
    print(line)
    
print("==" * 30)
lines = "".join(lines) #### 리스트 자료형을 문자열 가져오고자 할 때 사용
print(lines)

print("==" * 30)
str1 = 'abcdefg'
print(','.join(str1))

['1번째 줄입니다.\n', '2번째 줄입니다.\n', '3번째 줄입니다.\n', '4번째 줄입니다.\n', '5번째 줄입니다.\n', '6번째 줄입니다.\n', '7번째 줄입니다.\n', '8번째 줄입니다.\n', '9번째 줄입니다.\n', '10번째 줄입니다.\n', '11번째 줄입니다.\n', '12번째 줄입니다.\n', '13번째 줄입니다.\n', '14번째 줄입니다.\n', '15번째 줄입니다.\n', '16번째 줄입니다.\n', '17번째 줄입니다.\n', '18번째 줄입니다.\n', '19번째 줄입니다.\n', '20번째 줄입니다.\n', '21번째 줄입니다.\n', '22번째 줄입니다.\n', '23번째 줄입니다.\n', '24번째 줄입니다.\n', '25번째 줄입니다.\n', '26번째 줄입니다.\n', '27번째 줄입니다.\n', '28번째 줄입니다.\n', '29번째 줄입니다.\n', '30번째 줄입니다.\n', '31번째 줄입니다.\n', '32번째 줄입니다.\n', '33번째 줄입니다.\n', '34번째 줄입니다.\n', '35번째 줄입니다.\n', '36번째 줄입니다.\n', '37번째 줄입니다.\n', '38번째 줄입니다.\n', '39번째 줄입니다.\n', '40번째 줄입니다.\n']
1번째 줄입니다.

2번째 줄입니다.

3번째 줄입니다.

4번째 줄입니다.

5번째 줄입니다.

6번째 줄입니다.

7번째 줄입니다.

8번째 줄입니다.

9번째 줄입니다.

10번째 줄입니다.

11번째 줄입니다.

12번째 줄입니다.

13번째 줄입니다.

14번째 줄입니다.

15번째 줄입니다.

16번째 줄입니다.

17번째 줄입니다.

18번째 줄입니다.

19번째 줄입니다.

20번째 줄입니다.

21번째 줄입니다.

22번째 줄입니다.

23번째 줄입니다.

24번째 줄입니다.

25번째 줄입니다.

26번째 줄입니다.

27번째 줄입니다.

28번째 줄입니다.

29번째 줄입니다.

30번째 줄입니다.

31번째 줄입니다.

32번째 

In [21]:
f = open("test1.txt","r")
data = f.read() # 파일안에 있는 내용을 그대로 받아옴.
f.close()
print(data)

1번째 줄입니다.
2번째 줄입니다.
3번째 줄입니다.
4번째 줄입니다.
5번째 줄입니다.
6번째 줄입니다.
7번째 줄입니다.
8번째 줄입니다.
9번째 줄입니다.
10번째 줄입니다.
11번째 줄입니다.
12번째 줄입니다.
13번째 줄입니다.
14번째 줄입니다.
15번째 줄입니다.
16번째 줄입니다.
17번째 줄입니다.
18번째 줄입니다.
19번째 줄입니다.
20번째 줄입니다.
21번째 줄입니다.
22번째 줄입니다.
23번째 줄입니다.
24번째 줄입니다.
25번째 줄입니다.
26번째 줄입니다.
27번째 줄입니다.
28번째 줄입니다.
29번째 줄입니다.
30번째 줄입니다.
31번째 줄입니다.
32번째 줄입니다.
33번째 줄입니다.
34번째 줄입니다.
35번째 줄입니다.
36번째 줄입니다.
37번째 줄입니다.
38번째 줄입니다.
39번째 줄입니다.
40번째 줄입니다.



In [24]:
f = open("test2.txt","w")
for i in range(1, 31):
    f.write(f"{i}번째 입니다.\n")
f.close()
f = open("test2.txt","r")
data = f.read()
f.close()
print(data)

1번째 입니다.
2번째 입니다.
3번째 입니다.
4번째 입니다.
5번째 입니다.
6번째 입니다.
7번째 입니다.
8번째 입니다.
9번째 입니다.
10번째 입니다.
11번째 입니다.
12번째 입니다.
13번째 입니다.
14번째 입니다.
15번째 입니다.
16번째 입니다.
17번째 입니다.
18번째 입니다.
19번째 입니다.
20번째 입니다.
21번째 입니다.
22번째 입니다.
23번째 입니다.
24번째 입니다.
25번째 입니다.
26번째 입니다.
27번째 입니다.
28번째 입니다.
29번째 입니다.
30번째 입니다.



In [28]:
with open("test3.txt","w") as f:
    for i in range(1, 31):
        f.write("%d번째 입니다.\n" % i)
with open("test3.txt","r") as f:
    data = f.read()
print(data)

print("===" * 30)
with open("test3.txt","a") as f:
    for i in range(31, 41):
        f.write("%d번째 입니다.\n" % i)
with open("test3.txt","r") as f:
    data = f.read()
print(data)

1번째 입니다.
2번째 입니다.
3번째 입니다.
4번째 입니다.
5번째 입니다.
6번째 입니다.
7번째 입니다.
8번째 입니다.
9번째 입니다.
10번째 입니다.
11번째 입니다.
12번째 입니다.
13번째 입니다.
14번째 입니다.
15번째 입니다.
16번째 입니다.
17번째 입니다.
18번째 입니다.
19번째 입니다.
20번째 입니다.
21번째 입니다.
22번째 입니다.
23번째 입니다.
24번째 입니다.
25번째 입니다.
26번째 입니다.
27번째 입니다.
28번째 입니다.
29번째 입니다.
30번째 입니다.

1번째 입니다.
2번째 입니다.
3번째 입니다.
4번째 입니다.
5번째 입니다.
6번째 입니다.
7번째 입니다.
8번째 입니다.
9번째 입니다.
10번째 입니다.
11번째 입니다.
12번째 입니다.
13번째 입니다.
14번째 입니다.
15번째 입니다.
16번째 입니다.
17번째 입니다.
18번째 입니다.
19번째 입니다.
20번째 입니다.
21번째 입니다.
22번째 입니다.
23번째 입니다.
24번째 입니다.
25번째 입니다.
26번째 입니다.
27번째 입니다.
28번째 입니다.
29번째 입니다.
30번째 입니다.
31번째 입니다.
32번째 입니다.
33번째 입니다.
34번째 입니다.
35번째 입니다.
36번째 입니다.
37번째 입니다.
38번째 입니다.
39번째 입니다.
40번째 입니다.



In [30]:
#### class는 반복적으로 사용해야 하는 변수와 함수가 있는 경우
result = 0 # 연산을 할때마다 값 증가되거나 변하도록 한다.
result += 1 # result = result + 1 # result = 0 + 1 : 1
print(result)
result += 4 # result = result + 4 # result = 1 + 4 : 5
print(result)
result += 3 # result = result + 3 # result = 5 + 3 : 8
print(result)

1
5
8


In [35]:
result = 0 # 전역변수
def add(num):
    global result
    result += num

In [36]:
add(1) # result = result + 1 : result = 0 + 1
print(result) 
add(4) # result = result + 4 : result = 1 + 4
print(result)
add(3) # result = result + 3 : result = 5 + 3
print(result)

1
5
8


In [38]:
print(result) # 8
'''
add(3) # result = result + 3 : result = 8 + 3
print(result) # 11
'''

8


In [42]:
result1 = 0 # 전역변수
def add1(num):
    global result1
    result1 += num

In [43]:
add1(2)
print(result1)
print(result)
add1(3)
print(result1)
print(result)
add1(7)
print(result1) # 12
print(result) # 8

2
8
5
8
12
8


In [44]:
print(result1) # 12
print(result) # 8

12
8


In [ ]:
result2 = 0 # 전역변수
def add2(num):
    global result2
    result2 += num

In [47]:
class ClassAdd:
    result = 0
    def add(self, num):#class안에 있는 함수의 매개변수에는 self매개변수가 있어야 한다.
        self.result += num

In [51]:
a1 = ClassAdd() # result, add()
i = 10
l = [1,2,3,4]

a1.add(1)
print(a1.result)
a1.add(4)
print(a1.result)
a1.add(3)
print(a1.result)

1
5
8


In [52]:
print(a1.result)

8


In [54]:
a2 = ClassAdd() # result , add()
a2.add(2)
print(a2.result)
a2.add(3)
print(a2.result)
a2.add(7)
print(a2.result)

2
5
12


In [56]:
print(a1.result)
print(a2.result)

8
12


In [59]:
a3 = ClassAdd()
a3.add(3)
a3.add(9)
a3.add(5)

In [60]:
print(a1.result)
print(a2.result)
print(a3.result)

8
12
17


In [65]:
# class내에 있는 함수의 매개변수 self
class Calculator:
    result = 0 # 멤버변수, 멤버필드
    def add(self, num):
        self.result += num # self.result = self.result + num

In [68]:
cal1 = Calculator()
cal1.add(2) 
cal2 = Calculator()
cal2.add(3) 
print(cal1.result)
print(cal2.result)
print("==" * 30)
Calculator.add(cal1, 3)
print(cal1.result)
Calculator.add(cal2, 5)
print(cal2.result)
cal1.add(4) #  변수명이 self매개변수에게 넘어가도록 되어 있다.
cal2.add(10)  
print(cal1.result)
print(cal2.result)

2
3
5
8


In [69]:
cal3 = Calculator()
Calculator.add(cal3, 5)
cal3.add(3) # cal3변수가 add()함수의 self매개변수 전달이 된다.
print(cal3.result) # java에 this와 self는 같은 의미이다.

8


In [83]:
# 멤버 필드 초기화
class FourCal:
    def setData(self, num1, num2):
        self.first = num1
        self.second = num2
    def add(self):
        self.result = self.first + self.second
    def sub(self):
        self.result = self.first - self.second
    def mul(self):
        self.result = self.first * self.second
    def div(self):
        self.result = self.first / self.second

In [84]:
a = FourCal()
a.setData(10, 20) # 멤버필드 초기화(first, second)
print(a.first, a.second) 
a.add()
print(a.result)

10 20
30


In [86]:
a.sub()
print(a.result)
a.mul()
print(a.result)
FourCal.div(a) # a.div()
print(a.result)

-10
200
0.5


In [87]:
b = FourCal() # 변수 선언 : 객체 생성 : 클래스로 변수 선언 
FourCal.setData(b, 20, 10) # b.setData(20,10)
print(b.first, b.second)
# 1. 객체생성 
# 2. 멤버 필드 초기화

20 10


In [94]:
# 객체 생성과 동시에 멤버필드 초기화
class FourCal1:
    def __init__(self, num1, num2): ## 객체 생성시에 실행되는 함수 : 생성자
        self.first = num1           ## 멤버 필드를 초기화하기 위해서 사용
        self.second = num2
        print("객체 생성시 자동으로 실행") # 추가
    def add(self):
        self.result = self.first + self.second
    def sub(self):
        self.result = self.first - self.second
    def mul(self):
        self.result = self.first * self.second
    def div(self):
        self.result = self.first / self.second

In [91]:
b = FourCal1(20, 10) ### 객체생성과 동시에 멤버 필드 초기화
                     ## __init__()자동으로 실행이 됨
print(b.first, b.second)
b.add()
print(b.result)
b.sub()
print(b.result)
b.mul()
print(b.result)
b.div()
print(b.result)

20 10
30
10
200
2.0


In [95]:
c = FourCal1(30, 15)# __init__()실행이된 걸 확인 할수 있다.

객체 생성시 자동으로 실행


In [97]:
# 상속
class FourCal2: ### 선배가 이미 만들어 놓은 것(부모 클래스)
    def __init__(self, num1, num2): 
        self.first = num1           
        self.second = num2
    def add(self):
        self.result = self.first + self.second
    def div(self):
        self.result = self.first / self.second

In [98]:
class MoreFourCal(FourCal2): # FourCal2를 상속받아 옴 ( 자식클래스 )
    def sub(self):
        self.result = self.first - self.second
    def mul(self):
        self.result = self.first * self.second 
# 상속받아 왔으므로 암시적으로 아래 내용이 포함됨
#     def __init__(self, num1, num2): 
#         self.first = num1           
#         self.second = num2
#     def add(self):
#         self.result = self.first + self.second
#     def div(self):
#         self.result = self.first / self.second

In [101]:
d = MoreFourCal(4, 2)
print(d.first, d.second, sep =",")
d.add()
print(d.result)
d.sub()
print(d.result)
d.mul()
print(d.result)
d.div()
print(d.result)

4,2
6
2
8
2.0


In [105]:
e = MoreFourCal(0, 2)
e.div() # 0 / 2 = 0 : 부정
print(e.result)

e = MoreFourCal(2, 0)
# e.div() # 2 / 0 : 불능 # 오류발생
# print(e.result)

0.0


ZeroDivisionError: division by zero

In [109]:
class FourCal3: 
    def __init__(self, num1, num2): 
        self.first = num1           
        self.second = num2
    def add(self):
        self.result = self.first + self.second
    def div(self): # 불능을 생각 하지 않고 만들어서 오류가 발생
        self.result = self.first / self.second
class MoreFourCal3(FourCal3):
    def sub(self):
        self.result = self.first - self.second
    def mul(self):
        self.result = self.first * self.second 
#     def div(self): 
#         self.result = self.first / self.second
    def div(self): # 암시적으로 존재하는 상속 받은 함수를 재정의 : 오버라이딩
        if self.second == 0:
            self.result = 0
        else: 
            self.result = self.first / self.second

In [113]:
f = MoreFourCal3(2, 0) # first : 2 , second = 0 
f.div()
print(f.result)
f = MoreFourCal3(0,2) 
f.div()
print(f.result)
f = MoreFourCal3(4,2) 
f.div()
print(f.result)

0
0.0
2.0


In [ ]:
# 반복문 : 반복적으로 사용되는 규칙성을 가질 때 명령어를 한번만 사용
# 함수 : 반복문을 반복적으로 사용
# 클래스 : 변수와 함수를 반복적으로 만들어서 사용
# 모듈 : 반복적으로 사용되는 변수나 함수 그리고 클래스를 하나로 묶어 놓은 것 

In [149]:
import mod1 # 파일안에 있는 내용이 암시적으로 존재
print(mod1.PI)
result1 = mod1.sum1(20, 10)
print(result1)
dd = mod1.FourCal1(20, 10)
dd.add()
print(dd.result)

3.141592
30
객체 생성시 자동으로 실행
30


In [163]:
from mod1 import *

print(PI)
result1 = sum1(20, 10)
print(result1)
dd = FourCal1(20, 10)
dd.add()
print(dd.result)


3.141592
30
객체 생성시 자동으로 실행
30


In [138]:
### python에는 배열 자료형이 없다.
### switch문 대신 딕셔너리, 배열 대신 리스트 

### numpy는 숫자로 된 배열
import numpy as np 
num = np.random.randint(10)
print(num)

8


In [170]:
num = np.random.randint(10)
print(num)

1


In [172]:
# 1~ 10사이에 있는 값을 가는 1차원 배열
num = np.random.randint(10, size=6)
print(num) # [1 5 2 1 1 0]
l = [1,2,3,4,5]
print(l)

[1 5 2 1 1 0]
[1, 2, 3, 4, 5]


In [174]:
# 1~ 10사이에 있는 값을 가는 2차원 배열
num2 = np.random.randint(10, size=(3, 4)) # 3행 4열
print(num2)
# 2차원 배열 : 1차원 배열의 집합체
# 2차원의 행은 1차원 배열이다.
num3 = np.random.randint(10, size=(1, 4)) # 1행 4열
print(num3) # [[7 3 2 2]]

[[3 0 4 3]
 [5 5 1 9]
 [4 8 9 9]]
[[7 3 2 2]]


In [178]:
### 1차원배열과 리스트 비교
print(num) # [1 5 2 1 1 0]
#     열번호  0 1 2 3 4 5
#            6 5 4 3 2 1 -
print(l) # [1, 2, 3, 4, 5]
#           0  1  2  3  4 :index
#           5  4  3  2  1 -
print(l[2])
print(num[2])
print(l[-2])
print(num[-2])

[1 5 2 1 1 0]
[1, 2, 3, 4, 5]
3
2
4
1


In [184]:
# [1 5 2 1 1 0] 배열
# [1, 2, 3, 4, 5] 리스트
print(l[0:4])
print(num[0:4])
print(l[0:4:2])
print(num[0:4:2])
print(l[:4])
print(num[:4])
print(l[:])
print(num[:])
print(l[::-1])
print(num[::-1])
# indexing이나 slicing은 리스트나 1차원 배열은 같다.

[1, 2, 3, 4]
[1 5 2 1]
[1, 3]
[1 2]
[1, 2, 3, 4]
[1 5 2 1]
[1, 2, 3, 4, 5]
[1 5 2 1 1 0]
[5, 4, 3, 2, 1]
[0 1 1 2 5 1]


In [189]:
### 배열이나 리스트에 있는 값을 변경하는 방법도 같다.
print(l)
print(num)
print(l[2])
l[2] = 10
print(num[2])
num[2] = 10
print(num)

[1, 2, 10, 4, 5]
[1 5 2 1 1 0]
10
2
[ 1  5 10  1  1  0]


In [192]:
print(num2) # 2차원 배열 
#     0 1 2 3
#     4 3 2 1 -
# 0 [[3 0 4 3]  -3
# 1 [5 5 1 9]   -2
# 2 [4 8 9 9]]  -1
l2 = [[3, 0, 4, 3],[5, 5, 1, 9],[4, 8, 9, 9]]
#           0            1            2
#      0  1  2  3   0  1  2  3   0  1  2  3   
#          -3           -2           -1
#      4  3  2  1   4  3  2  1   4  3  2  1 -
print(l2) # 리스트

[[3 0 4 3]
 [5 5 1 9]
 [4 8 9 9]]
[[3, 0, 4, 3], [5, 5, 1, 9], [4, 8, 9, 9]]


In [200]:
print(num2[0])
print(l2[0])
print(num2[1])
print(l2[1])
print(l2[1][1])
print(num2[1][1]) # 리스트 스타일
# print(l2[1 , 1]) # 리스트에서는 배열 방식은 사용할 수 없다.
print(num2[1, 1]) # 배열 스타일
print(l2[-2][-2])
print(num2[-2][-2]) # 리스트 스타일
print(num2[-2, -2]) # 배열 스타일
#print(num2[행, 열])

[3 0 4 3]
[3, 0, 4, 3]
[5 5 1 9]
[5, 5, 1, 9]
5
5
5
1
1
1


In [215]:
# slicing
# 2차원 배열(num2)
#     0 1 2 3
#     4 3 2 1 -
# 0 [[3 0 4 3]  -3
# 1  [5 5 1 9]   -2
# 2  [4 8 9 9]]  -1
# 리스트(l2)
#    [[3, 0, 4, 3],[5, 5, 1, 9],[4, 8, 9, 9]]
#           0            1            2
#      0  1  2  3   0  1  2  3   0  1  2  3   
#          -3           -2           -1
#      4  3  2  1   4  3  2  1   4  3  2  1 -
print(l2[0:2])
print(num2[0:2])
print(l2[1][0:2])
print(num2[1][0:2])
print(l2[0][0:2])
print(l2[1][0:2])
print(l2[0:2])
# print(l2[0:2][0:2]) 
# print(num2[0:2][0:2]) 리스트 스타일로는 열이 분리되지 않는다.
# 원하는 행에 있는 원하는 열을 가지고 올 수 있다.
print(num2[0:2, 0:2]) 
#           행, 열    # 0행과 1행에서 0열과 1열만 가져옴
print(l2[1][::2])
print(num2[::2, ::2]) # 행과 열을 한칸 띄기

### 열을 한칸씩 건너 띄우기
print(num2[: , ::2])
### 행을 한칸씩 건너 띄우기
print(num2[::2, :])

[[3, 0, 4, 3], [5, 5, 1, 9]]
[[3 0 4 3]
 [5 5 1 9]]
[5, 5]
[5 5]
[3, 0]
[5, 5]
[[3, 0, 4, 3], [5, 5, 1, 9]]
[[3 0]
 [5 5]]
[5, 1]
[[3 4]
 [4 9]]
[[3 4]
 [5 1]
 [4 9]]
[[3 0 4 3]
 [4 8 9 9]]


In [226]:
print(num2)
# 행을 2 1 0순으로 출력
print(num2[::-1])
# 열을 3 2 1 0순으로 출력
print(num2[:, ::-1])
# 행과 열을 모두 거꾸로 출력
print(num2[::-1, ::-1])
### 첫번째 행만 출력
print(num2[0])
print(num2[0, :])
### 첫번째 열만 출력
print(num2[:, 0])
### 두번째 열만 출력
print(num2[:, 1])
# 1행 1열의 값을 99로 변경하시오.
num2[0,0] = 99
print(num2)

[[3 0 4 3]
 [5 5 1 9]
 [4 8 9 9]]
[[4 8 9 9]
 [5 5 1 9]
 [3 0 4 3]]
[[3 4 0 3]
 [9 1 5 5]
 [9 9 8 4]]
[[9 9 8 4]
 [9 1 5 5]
 [3 4 0 3]]
[3 0 4 3]
[3 0 4 3]
[3 5 4]
[0 5 8]
[[99  0  4  3]
 [ 5  5  1  9]
 [ 4  8  9  9]]


In [236]:
### 배열을 만드는 다른 방법
#  0~8까지 9개의 수를 가지는 2차원 배열
i = np.arange(9).reshape(3,3)
print(i)
#  0~11까지 12개의 수를 가지는 2차원 배열
i1 = np.arange(12).reshape(3,4)
i2 = np.arange(12).reshape(4,3)
print(i1)
print(i2)
#  11~ 19까지 수를 가지는 2차원 배열
i3 = np.arange(11,20).reshape(3,3)
print(i3)
# 1~3까지의 수를 가지는 1행짜리 2차원배열
i4 = np.arange(1,4).reshape(1,3)
print(i4)
# 1~3까지의 수를 가지는 3행짜리 2차원배열
i5 = np.arange(1,4).reshape(3,1)
print(i5)
# 1~3까지의 수를 가지는 1차원배열
i6 = np.arange(1,4).reshape(3)
print(i6)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]
[[1 2 3]]
[[1]
 [2]
 [3]]
[1 2 3]


In [240]:
# array함수를 이용한 배열을 만들자.
# 2,5,7을 가지는 1차원 배열을 만드시오.
ii1 = np.array([2,5,7])
print(ii1)
# [1,2,3],[4,5,6],[7,8,9]을 가지는 2차원배열 만들자.
ii2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(ii2)
ii3 = np.array([[[1,2,3],[4,5,6],[7,8,9]], # 0면
                [[1,2,3],[4,5,6],[7,8,9]], # 1면
                [[1,2,3],[4,5,6],[7,8,9]]]) # 2면
print(ii3)
print(ii1[2]) # ii1[열]
print(ii2[2,2]) # ii2[행, 열]
print(ii3[1, 2, 2]) # ii3[면, 행, 열]

[2 5 7]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
7
9
9


In [248]:
x = np.array([1, 2, 3]) # 1차원 배열
y = np.array([3, 2, 1]) # 1차원 배열
print(x)
print(y)
z = np.concatenate([x,y])
print(z)
v = [99,99,99] # 리스트
z = np.concatenate([x,y,v])
print(z)
l1 = [1,2,3] # 리스트
l2 = [4,5,6] # 리스트
l3 = [7,8,9] # 리스트
z = np.concatenate([l1,l2,l3])
print(z)
z = np.concatenate([[1,2,3],[4,5,6],[7,8,9]])
print(z)
z = np.concatenate([[1,2,3],[4],[7,8]])
print(z)

[1 2 3]
[3 2 1]
[1 2 3 3 2 1]
[ 1  2  3  3  2  1 99 99 99]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 7 8]


In [257]:
x2 = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])
#z = np.concatenate([x2 ,grid]) # 차원이 다르면 사용할 수 없다.
z = np.vstack([x2 ,grid]) # 열의 크기가 다르면 안됨
print(z)
z = np.vstack([grid,x2])
print(z)
y2 = np.array([[1],[2]])
print(y2)
print(grid)
z = np.hstack([grid,y2]) # 행의 크기가 다르면 합쳐지지 않는다.
print(z)
z = np.hstack([y2,grid])
print(z)

[[1 2 3]
 [9 8 7]
 [6 5 4]]
[[9 8 7]
 [6 5 4]
 [1 2 3]]
[[1]
 [2]]
[[9 8 7]
 [6 5 4]]
[[9 8 7 1]
 [6 5 4 2]]
[[1 9 8 7]
 [2 6 5 4]]


In [265]:
# 유니버설 함수(UFuncs)
x = np.arange(4)
print(x)
j = np.array([5,5,5,5])
print(j)
y = x + j  # [0 1 2 3] + [5 5 5 5] = [5 6 7 8]
print(y)

y = x + 5 # [0 1 2 3] + 5 => [0 1 2 3] + [5 5 5 5]
print(y)
y = np.add(x , 5)
y = x - 5
print(y)
y = np.subtract(x, 5)
print(y)
y = x * 5
print(y)
y = np.multiply(x, 5)
print(y)

[0 1 2 3]
[5 5 5 5]
[5 6 7 8]
[5 6 7 8]
[-5 -4 -3 -2]
[-5 -4 -3 -2]
[ 0  5 10 15]
[ 0  5 10 15]


In [271]:
a = np.arange(3)
print(a)
b = np.arange(3)[:,np.newaxis] # 1열짜리 배열
print(b)
c = a + b # 크기가 같게 만들어 주는 것을 브로드케스트
print(c)
M = np.ones((3,3))
print(M)
o = np.zeros((3,3))
print(o)
c = a + M # 브로드케스트 
print(c)

[0 1 2]
[[0]
 [1]
 [2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


In [273]:
# 배열 분할하기
x = np.array([1, 2, 3, 99, 99, 3, 2, 1,3])
x1, x2, x3 = np.split(x, 3)
print(x1, x2 , x3)

x1 , x2 , x3, x4 = np.split(x, [3,5,7])
print(x1, x2 , x3, x4)
# 3번째까지, 5번째까지, 7번째까지 , 나머지

[1 2 3] [99 99  3] [2 1 3]
[1 2 3] [99 99] [3 2] [1 3]


In [276]:
grid = np.arange(16).reshape((4, 4))
print(grid)
y1 , y2 = np.vsplit(grid, [2])
print(y1)
print(y2)
y1 , y2 = np.hsplit(grid, [2])
print(y1)
print(y2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0 1 2 3]
 [4 5 6 7]] [[ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]] [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [291]:
import numpy as np
x = np.random.rand(3)
print(x)
x = np.random.rand(6)
print(x)
x = np.random.rand(1000000) # 0 ~ 1사이의 값을 가지는 1차원 배열
print(x)
%timeit sum(x) 
%timeit np.sum(x) 

#94.1 ms ± 4.5 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
#1.63 ms ± 448 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

[0.95151256 0.6870814  0.86709526]
[0.47412225 0.4574557  0.46836517 0.19949639 0.20794931 0.21567681]
[0.57257954 0.89964684 0.63811173 ... 0.22844415 0.14505182 0.18542254]
1.06 ms ± 169 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [296]:
M = np.random.random((3, 4))
print(M)
print(M.sum())
print(M.min())
### 열에서 최소값
print(M.min(axis=0)) # x축 기준
### 행에 대한 최소값 
print(M.min(axis=1)) # y 축기준

[[0.15487452 0.17376509 0.36558943 0.15342648]
 [0.72780961 0.28878071 0.16728728 0.21661847]
 [0.33939047 0.2471052  0.46196749 0.71292035]]
4.0095351121616725
0.15342648160296835
[0.15487452 0.17376509 0.16728728 0.15342648]
[0.15342648 0.16728728 0.2471052 ]


In [300]:
import pandas as pd
data = pd.read_csv("https://raw.githubusercontent.com/SoongMoo/soldesk2110/main/%EC%B0%B8%EA%B3%A0%EC%9E%90%EB%A3%8C/NumPy/data/president_heights.csv")
# print(data)
heights = np.array(data['height(cm)'])
print(heights)
print(heights.mean()) # 평균값
print(heights.min()) # 최소값 0 사분위
print(heights.max()) # 최대값 4 사분위
print(heights.std()) # 표준편차
print(np.median(heights)) # 중앙값  2사분위
print(np.percentile(heights, 25)) # 1 사분위 25%
print(np.percentile(heights, 75)) # 3 사분위 75%

[189 170 189 163 183 171 185 168 173 183 173 173 175 178 183 193 178 173
 174 183 183 168 170 178 182 180 183 178 182 188 175 179 183 193 182 183
 177 185 188 188 182 185]
179.73809523809524
163
193
6.931843442745892
182.0
174.25
183.0


In [303]:
# 비교 연산자
x = np.array([1, 2, 3, 4, 5])
print( x > 3)
print(np.greater(x, 3))
print( x < 3 )
print(np.less(x, 3))
print(x <= 3)
print(np.less_equal(x, 3))
print(x == 3)
print(np.equal(x, 3))
print(x != 3)
print(np.not_equal(x, 3))

[False False False  True  True]
[False False False  True  True]
[ True  True False False False]
[ True  True False False False]
[ True  True  True False False]
[ True  True  True False False]
[False False  True False False]
[False False  True False False]
[ True  True False  True  True]
[ True  True False  True  True]


In [315]:
rainfall = pd.read_csv("https://raw.githubusercontent.com/SoongMoo/soldesk2110/main/%EC%B0%B8%EA%B3%A0%EC%9E%90%EB%A3%8C/NumPy/data/Seattle2014.csv")
inches = np.array(rainfall['PRCP']) / 254
# print(inches)
# 강수량이 0.5이상인 날은 몇일이나 되나요?
# print(inches > 0.5) 
print(False + False) # False는 0
print(True + True) # True는 1
print(np.sum(inches > 0.5))
# 강수량이 0.5에서 0.8 사이인 날은 몇일이나 되나요?
print(np.sum((inches >= 0.5) & (inches <=0.8)))
# 강수량이 0.5보다 적게 오고 0.8보다 많이 온날은?
print(np.sum(~((inches >= 0.5) & (inches <=0.8))))
print(np.sum((inches < 0.5) | (inches > 0.8)))

# 비가 안온 날은 몇일 일까요?
print(np.sum(inches == 0))
# 비가 온날은 몇일 입니까?
print(np.sum(inches != 0))

0
2
37
26
339
339
215
150


In [317]:
# 정렬
x = np.array([2, 1, 4, 3, 5])
print(np.sort(x))
print(x)
y = np.sort(x)
print(y)
x.sort() # 정렬이 되어서 저장
print(x)

[1 2 3 4 5]
[2 1 4 3 5]
[1 2 3 4 5]
[1 2 3 4 5]


In [321]:
x = np.random.randint(0,10,(4,6))
print(x)
# 행단위 정렬
print(np.sort(x))
print(np.sort(x, axis = 1)) # y축기준
# 열단위 정렬
print(np.sort(x, axis = 0)) # x축기준

[[8 4 9 7 0 2]
 [1 7 9 4 4 1]
 [0 2 5 0 4 9]
 [2 3 1 0 8 4]]
[[0 2 4 7 8 9]
 [1 1 4 4 7 9]
 [0 0 2 4 5 9]
 [0 1 2 3 4 8]]
[[0 2 4 7 8 9]
 [1 1 4 4 7 9]
 [0 0 2 4 5 9]
 [0 1 2 3 4 8]]
[[0 2 1 0 0 1]
 [1 3 5 0 4 2]
 [2 4 9 4 4 4]
 [8 7 9 7 8 9]]


In [325]:
# 파티션 나누기
print(x)
# 작은 수 3개를 앞으로 나머지는 뒤로
print(np.partition(x,3, axis=0 )) # 열 단위 , x축기준, 순서는 없다
print(np.partition(x,3, axis=1 )) # 행 단위 , y축기준, 순서는 없다

[[8 4 9 7 0 2]
 [1 7 9 4 4 1]
 [0 2 5 0 4 9]
 [2 3 1 0 8 4]]
[[0 2 5 0 0 1]
 [1 3 1 0 4 2]
 [2 4 9 4 4 4]
 [8 7 9 7 8 9]]
[[0 2 4 7 8 9]
 [1 1 4 4 7 9]
 [0 0 2 4 5 9]
 [0 1 2 3 4 8]]
